language: objective-c
osx_image: xcode7
xcode_project: Framework/YYModel.xcodeproj
xcode_scheme: YYModel
before_install:
- brew update
- brew upgrade xctool
script:
- xctool -project Framework/YYModel.xcodeproj -scheme YYModel build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
- xctool -project Framework/YYModel.xcodeproj -scheme YYModel test -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES
after_success:
- bash <(curl -s https://codecov.io/bash)